
openapi: 3.0.0
info:
  version: 0.9.0
  title: Users API
  description: API para el manejo de usuarios.

tags:
- name: Users
  description: Operaciones relacionadas con usuarios
- name: Role Admin
  description: Operaciones que solo puede realizar un usuario con rol de administrador.
- name: Role User
  description: Operaciones que puede realizar cualquier usuario registrado.

paths:
  /api/users/admin/getAll:
    get:
      tags:
      - Users
      - Role Admin
      summary: Obtener todos los usuarios.
      security:
        - CookieAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Limite de usuarios a retornar.
        - in: query
          name: page
          schema:
            type: integer
          description: Número de página.
      responses:
        200:
          description: Listado de usuarios.
        400:
          description: No se han encontrado usuarios.
        401:
          description: No está autorizado.
        500:
          description: Error interno del servidor.

  /api/users/admin/update/premium/{id}:
    patch:
      tags:
      - Users
      - Role Admin
      summary: Actualizar rol de un usuario a premium.
      security:
        - CookieAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: false
          description: ID del usuario.
      responses:
        200:
          description: Rol del usuario actualizado correctamente.
        400:
          description: Error al intentar actualizar el rol del usuario.
        401:
          description: No está autorizado.
        403:
          description: No tiene permisos para realizar esta acción.
        500:
          description: Error interno del servidor.

  /api/users/admin/delete/inactives:
    delete:
      tags:
      - Users
      - Role Admin
      summary: Eliminar los usuarios que no han tenido actividad en los últimos 30 días.
      security:
        - CookieAuth: []
      responses:
        200:
          description: Usuarios inactivos eliminados correctamente.
        400:
          description: Error al intentar eliminar los usuarios inactivos.
        401:
          description: No está autorizado.
        403:
          description: No tiene permisos para realizar esta acción.

  
  /api/users/{uid}/documents:
    post:
      tags:
      - Users
      - Role User
      summary: Sube uno o múltiples documentos para un usuario.
      description: Permite a un usuario subir documentos que serán almacenados y asociados a su perfil.
      parameters:
        - in: path
          name: uid
          required: true
          description: ID único del usuario.
          schema:
            type: string
      requestBody:
        description: Datos del documento a subir.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                documents:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: Documentos subidos correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


  /api/users/update:
    patch:
      tags:
      - Users
      - Role User
      summary: Actualizar información del usuario.
      security:
        - CookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                age:
                  type: integer
                phone:
                  type: string
      responses:
        200:
          description: Información del usuario actualizada correctamente.
        400:
          description: Error en los datos proporcionados.
        401:
          description: No está autorizado.
        500:
          description: Error interno del servidor.

  /api/users/delete:
    delete:
      tags:
      - Users
      - Role User
      summary: Eliminar cuenta de usuario.
      security:
        - CookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description: Usuario eliminado correctamente.
        400:
          description: Error al intentar eliminar el usuario.
        500:
          description: Error al intentar eliminar el usuario.

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: auth
